allTeams = [
/************************************************************ ABLANIA */
/*Dinamo_Durrësi*/"alb/Dinamo_Durr%C3%ABsi",
/*Dinamo_Shkodra*/"alb/Dinamo_Shkodra",
/*FC_Dinamo_City*/"alb/FK_Dinamo_Tirana",
/*FK_Apolonia_Fier*/"alb/KF_Apolonia_Fier",
/*FK_Partizani_Tirana*/"alb/FK_Partizani_Tirana",
/*Flamurtari_FC*/"alb/Flamurtari_Vlor%C3%AB",
/*KF_Albpetrol_Patos*/"alb/KF_Albpetrol",
/*KF_Besa_Kavajë*/"alb/Besa_Kavaj%C3%AB",
/*KF_Besëlidhja_Lezhë*/"alb/Bes%C3%ABlidhja_Lezh%C3%AB",
/*KF_Burreli*/"alb/KS_Burreli",
/*KF_Bylis*/"alb/KF_Bylis_Ballsh",
/*KF_Egnatia*/"alb/FK_Egnatia",
/*KF_Elbasani*/"alb/KF_Elbasani",
/*KF_Erzeni*/"alb/KF_Erzeni",
/*KF_Gramozi*/"alb/KS_Gramozi_Ersek%C3%AB",
/*KF_Iliria*/"alb/KS_Iliria",
/*FC_Kamza*/"alb/FC_Kamza",
/*KF_Korabi_Peshkopi*/"alb/KF_Korabi_Peshkopi",
/*FK_Kukësi*/"alb/FK_Kuk%C3%ABsi",
/*KF_Laçi*/"alb/KF_La%C3%A7i",
/*KF_Luftëtari*/"alb/Luft%C3%ABtari_Gjirokast%C3%ABr",
/*KF_Lushnja*/"alb/KS_Lushnja",
/*KF_Naftëtari*/"alb/KF_Naft%C3%ABtari",
/*KF_Përmeti*/"alb/KF_P%C3%ABrmeti",
/*KF_Selenica*/"alb/KS_Selenic%C3%AB",
/*KF_Shkëndija_Tiranë*/"alb/Shkendija_Tirane",
/*KF_Shkumbini*/"alb/Shkumbini_Peqin",
/*KF_Skënderbeu_Korçë*/"alb/KF_Sk%C3%ABnderbeu_Kor%C3%A7%C3%AB",
/*KF_Sopoti*/"alb/Sopoti_Librazhd",
/*KF_Spartak_Tirana*/"alb/KF_Spartaku_Tiran%C3%AB",
/*KF_Tekstilisti_Stalin*/"alb/KF_Tekstilisti_Stalin",
/*KF_Teuta_Durrës*/"alb/KF_Teuta_Durr%C3%ABs",
/*KF_Tirana*/"alb/KF_Tirana",
/*KF_Tomori*/"alb/FK_Tomori_Berat",
/*KF_Vllaznia_Shkodër*/"alb/KF_Vllaznia_Shkod%C3%ABr",
/*KS_Kastrioti*/"alb/KS_Kastrioti",
/*KS_Pogradeci*/"alb/KF_Pogradeci",
/*KS_Studenti*/"alb/KS_Studenti",
/*Luftëtari_Enver_Hoxha_Tiranë*/"alb/Luft%C3%ABtari_Enver_Hoxha_Tiran%C3%AB",
/*Spartaku_Shkodër*/"alb/Spartaku_Shkod%C3%ABr",





"aut/SK_Rapid_Wien",
"aut/Wiener_Sportclub",
"aut/Wiener_AF",
"aut/Wiener_AC",
"aut/1._Simmeringer_SC",
"aut/First_Vienna_FC",
"aut/Floridsdorfer_AC",
"aut/SV_Amateure",
"aut/ASV_Hertha",
"aut/SC_Rudolfsh%C3%BCgel",
"aut/Vienna_Cricket_and_Football-Club",
"aut/SC_Wacker",
"aut/VfB_Admira_Wacker_M%C3%B6dling",
"aut/FC_Admira_Wacker_M%C3%B6dling_merge",
"aut/Hakoah_Vienna",
"aut/FC_Ostmark",
"aut/SK_Slovan_HAC",
"aut/Brigittenauer_AC",
"aut/SC_Nicholson",
"aut/FC_Wien",
"aut/SC_Libertas",
"aut/SV_Donau",
"aut/Favoritner_AC",
"aut/Post_SV",
"aut/SC_Helfort",
"aut/SC_Rapid_Oberlaa",
"aut/SC_Ostbahn_XI",
"aut/SCR_Hochst%C3%A4dt",
"aut/SK_Vorw%C3%A4rts_Steyr",
"aut/SK_Sturm_Graz",
"aut/SV_Gloggnitz",
"aut/LASK_Linz",
"aut/1._Wiener_Neust%C3%A4dter_SC",
"aut/FS_Elektra",
"aut/Grazer_AK",
"aut/Kapfenberger_SV",
"aut/Favoritner_SK_Blau_Wei%C3%9F",
"aut/Grazer_SC",
"aut/Salzburger_AK_1914",
"aut/SV_Austria_Salzburg",





"aut/FC_Stadlau",
"aut/Schwarz-Wei%C3%9F_Bregenz",
"aut/ESV_Austria_Graz",
"aut/Kremser_SC",
"aut/SC_Olympia_33",
"aut/WSV_Donawitz",
"aut/SVS_Linz",
"aut/1._Schwechater_SC",
"aut/FC_Dornbirn",
"aut/FC_K%C3%A4rnten",
"aut/FC_Wacker_Innsbruck",
"aut/SC_Eisenstadt",
"aut/WSG_Radenthein",
"aut/WSG_Wattens",
"aut/V%C3%96EST_Linz",
"aut/Donawitzer_SV_Alpine",
"aut/SK_Bischofshofen",
"aut/SV_Admira_Wiener_Neustadt",
"aut/Radenthein/Villacher_SV",
"aut/SC_Neusiedl",
"aut/Union_Wels",
"aut/SV_Sankt_Veit",
"aut/SV_Spittal/Drau",
"aut/FC_Tirol_Innsbruck",
"aut/SKN_St._P%C3%B6lten",
"aut/SV_Ried",
"aut/SC_Austria_Lustenau",
"aut/ASK%C3%96_Pasching",
"aut/SV_Mattersburg",
"aut/FC_Wacker_Innsbruck_(2002)",
"aut/SC_Rheindorf_Altach",
"aut/SK_Austria_K%C3%A4rnten",
"aut/SC_Wiener_Neustadt",
"aut/Wolfsberger_AC",
"aut/SV_Gr%C3%B6dig",
"aut/TSV_Hartberg",
"aut/WSG_Swarovski_Tirol",
"aut/SK_Austria_Klagenfurt_(2007)",
"aut/FC_Blau-Wei%C3%9F_Linz",
"bel/R.F.C._de_Li%C3%A8ge",





"bel/R._Antwerp_F.C.",
"bel/Sporting_Club_de_Bruxelles",
"bel/Racing_Club_de_Bruxelles",
"bel/R._L%C3%A9opold_Uccle_Forestoise",
"bel/Club_Brugge",
"bel/Union_F.C._d%27Ixelles",
"bel/Athletic_and_Running_Club_de_Bruxelles",
"bel/K._Beerschot_V.A.C.",
"bel/Skill_F.C._de_Bruxelles",
"bel/R.C.S._Vervi%C3%A9tois",
"bel/Cercle_Brugge_K.S.V.",
"bel/R._Union_Saint-Gilloise",
"bel/Daring_Club_de_Bruxelles",
"bel/K.V._Kortrijk",
"bel/R.E._Sport%27s_Club",
"bel/K.R.C._Gent-Zeehaven",
"bel/Standard_Li%C3%A8ge",
"bel/K.R.C._Mechelen",
"bel/K.A.A._Gent",
"bel/R._Uccle_Sport",
"bel/K.F.C._Rhodienne-De_Hoek",
"bel/R.S.C._Anderlecht",
"bel/KV_Mechelen",
"bel/K_Berchem_Sport",
"bel/R.W.D._Molenbeek",
"bel/R.F.C._Tilleur",
"bel/CS_La_Forestoise",
"bel/Lierse_S.K.",
"bel/K._Tubantia_Borgerhout_V.K.",
"bel/R.R.F.C._Montegn%C3%A9e",
"bel/K.V._Turnhout",
"bel/K._Lyra",
"bel/Belgica_FC_Edegem",
"bel/R.O.C._de_Charleroi-Marchienne",
"bel/K.V.K._Tienen",
"bel/K_Boom_FC",
"bel/V.C._Eendracht_Aalst_2002",
"bel/K._Sint-Niklase_S.K.E.",
"bel/R._Charleroi_S.C.",
"bel/K._Stade_Leuven",





"bel/Beringen_FC",
"bel/R.F.C._Tournai",
"bel/K._Waterschei_S.V._Thor_Genk",
"bel/K._Sint-Truidense_V.V.",
"bel/K.F.C._Germinal_Beerschot",
"bel/Patro_Eisden",
"bel/KFC_Diest",
"bel/K.S.V._Waregem",
"bel/K.S.K._Beveren",
"bel/Crossing_Club_Schaerbeek",
"bel/A.S.V._Oostende_K.M.",
"bel/K.S.C._Lokeren_Oost-Vlaanderen",
"bel/K.R.C._Genk",
"bel/R.A.A._Louvi%C3%A9roise",
"bel/KSC_Hasselt",
"bel/K.S.K._Tongeren",
"bel/R.F.C._Seraing_(1904)",
"bel/R._Jet_Wavre",
"bel/K.F.C._Lommel_S.K.",
"bel/K.V._Oostende",
"bel/K.R.C._Zuid-West-Vlaanderen",
"bel/R.E._Mouscron",
"bel/K.V.C._Westerlo",
"bel/K.F.C._Verbroedering_Geel",
"bel/R.A.E.C._Mons_(1910)",
"bel/K._Beringen-Heusden-Zolder",
"bel/FC_Brussels",
"bel/S.V._Zulte-Waregem",
"bel/K.S.V._Roeselare",
"bel/F.C._Verbroedering_Dender_E.H.",
"bel/A.F.C._Tubize",
"bel/K.A.S._Eupen",
"bel/Oud-Heverlee_Leuven",
"bel/Waasland-Beveren",
"bel/Royal_Mouscron-P%C3%A9ruwelz",
"bel/K_Beerschot_VA",
"bel/R.F.C._Seraing_(1922)",
"bel/R.W.D._Molenbeek_(2015)",
"eng/Accrington_F.C.",
"eng/Aston_Villa_F.C.",





"eng/Blackburn_Rovers_F.C.",
"eng/Bolton_Wanderers_F.C.",
"eng/Burnley_F.C.",
"eng/Darwen_F.C._(1870)",
"eng/Derby_County_F.C.",
"eng/Everton_F.C.",
"eng/Manchester_United_F.C.",
"eng/Nottingham_Forest_F.C.",
"eng/Notts_County_F.C.",
"eng/Preston_North_End_F.C.",
"eng/Sheffield_United_F.C.",
"eng/Sheffield_Wednesday_F.C.",
"eng/Stoke_City_F.C.",
"eng/Sunderland_A.F.C.",
"eng/West_Bromwich_Albion_F.C.",
"eng/Wolverhampton_Wanderers_F.C.",
"eng/Birmingham_City_F.C.",
"eng/Liverpool_F.C.",
"eng/Bury_F.C.",
"eng/Newcastle_United_F.C.",
"eng/Manchester_City_F.C.",
"eng/Glossop_North_End_A.F.C.",
"eng/Grimsby_Town_F.C.",
"eng/Middlesbrough_F.C.",
"eng/Arsenal_F.C.",
"eng/Bristol_City_F.C.",
"eng/Chelsea_F.C.",
"eng/Bradford_City_A.F.C.",
"eng/Leicester_City_F.C.",
"eng/Tottenham_Hotspur_F.C.",
"eng/Oldham_Athletic_A.F.C.",
"eng/Bradford_(Park_Avenue)_A.F.C.",
"eng/Huddersfield_Town_A.F.C.",
"eng/Cardiff_City_F.C.",
"eng/West_Ham_United_F.C.",
"eng/Leeds_United_F.C.",
"eng/Portsmouth_F.C.",
"eng/Blackpool_F.C.",
"eng/Brentford_F.C.",
"eng/Charlton_Athletic_F.C.",





"eng/Fulham_F.C.",
"eng/Luton_Town_F.C.",
"eng/Ipswich_Town_F.C.",
"eng/Leyton_Orient_F.C.",
"eng/Northampton_Town_F.C.",
"eng/Southampton_F.C.",
"eng/Coventry_City_F.C.",
"eng/Queens_Park_Rangers_F.C.",
"eng/Crystal_Palace_F.C.",
"eng/Norwich_City_F.C.",
"eng/Carlisle_United_F.C.",
"eng/Brighton_%26_Hove_Albion_F.C.",
"eng/Swansea_City_A.F.C.",
"eng/Watford_F.C.",
"eng/Oxford_United_F.C.",
"eng/Wimbledon_F.C.",
"eng/Millwall_F.C.",
"eng/Swindon_Town_F.C.",
"eng/Barnsley_F.C.",
"eng/Wigan_Athletic_F.C.",
"eng/Reading_F.C.",
"eng/Hull_City_A.F.C.",
"eng/AFC_Bournemouth",
"eir/Clarence_F.C.",
"eir/Cliftonville_F.C.",
"eir/Derry_Olympic_F.C.",
"eir/Glentoran_F.C.",
"eir/Lancashire_Fusiliers_F.C.",
"eir/Ligoniel_F.C.",
"eir/Linfield_F.C.",
"eir/Lisburn_Distillery_F.C.",
"eir/Milford_F.C.",
"eir/Milltown_F.C.",
"eir/Oldpark_F.C.",
"eir/Ulster_F.C.",
"eir/YMCA_F.C._(Belfast)",
"nld/GVC_(football_club)",
"nld/HV_Victoria",
"nld/HVV_Den_Haag",
"nld/Koninklijke_HFC",





"nld/RAP_(football_club)",
"nld/RC_en_VV_Rotterdam",
"nld/Sparta_Rotterdam",
"nld/VVA/Spartaan",
"sco/Abercorn_F.C.",
"sco/Cambuslang_F.C.",
"sco/Celtic_F.C.",
"sco/Clyde_F.C.",
"sco/Cowlairs_F.C.",
"sco/Dumbarton_F.C.",
"sco/Dundee_F.C.",
"sco/Heart_of_Midlothian_F.C.",
"sco/Leith_Athletic_F.C.",
"sco/Rangers_F.C.",
"sco/Renton_F.C.",
"sco/St_Bernard%27s_F.C.",
"sco/St_Mirren_F.C.",
"sco/Third_Lanark_A.C.",
"sco/Vale_of_Leven_F.C.",
"nld/Rapiditas_Rotterdam",
"sco/Hibernian_F.C.",
"nld/HBS_Craeyenhout",
"eir/North_Staffordshire_Regiment_F.C.",
"eir/Belfast_Celtic_F.C.",
"nir/Belfast_Celtic_F.C..",
"sco/Partick_Thistle_F.C.",
"sco/Kilmarnock_F.C.",
"eir/Royal_Scots_F.C.",
"sco/Greenock_Morton_F.C.",
"sco/Queen%27s_Park_F.C.",
"eir/Derry_Celtic_F.C.",
"eir/St_Columb%27s_Court_F.C.",
"eir/Bohemian_F.C.",
"sco/Port_Glasgow_Athletic_F.C.",





"sco/Airdrieonians_F.C._(1878)",
"sco/Motherwell_F.C.",
"eir/King%27s_Own_Scottish_Borderers_F.C.",
"eir/Shelbourne_F.C.",
"sco/Falkirk_F.C.",
"sco/Aberdeen_F.C.",
"sco/Hamilton_Academical_F.C.",
"mlt/Floriana_F.C.",
"rou/Olympia_Bucure%C8%99ti",
"mlt/Sliema_Wanderers_F.C.",
"rou/Colentina_Bucure%C8%99ti",
"mlt/St. Joseph%27s United",
"mlt/Boys Empire League",
"rou/United_Ploie%C8%99ti",
"mlt/Malta University",
"sco/Raith_Rovers_F.C.",
"mlt/%C4%A6amrun_Spartans_F.C.",
"mlt/St._George%27s_F.C.",
"mlt/Valletta_F.C.",
"eir/Glenavon_F.C.",
"swe/IFK_G%C3%B6teborg",
"swe/%C3%96rgryte_IS",
"swe/AIK_Fotboll",
"swe/Djurg%C3%A5rdens_IF_Fotboll",
"mlt/Vittoriosa_Stars_F.C.",
"rou/Cercul_Atletic_Bucure%C8%99ti",
"rou/Bukarester_FC",
"swe/IFK_Uppsala_Fotboll",
"mlt/Msida_Saint-Joseph_F.C.",
"eir/Tritonville_F.C.",





"swe/IFK_Norrk%C3%B6ping",
"rou/Uniunea_Sportiv%C4%83_Bucure%C8%99ti",
"mlt/Senglea_Athletic_F.C.",
"sco/Ayr_United_F.C.",
"rou/Rom%C3%A2no-American%C4%83_Bucure%C8%99ti",
"mlt/Cottonera_F.C.",
"rou/Prahova_Ploie%C8%99ti",
"rou/Col%C8%9Bea_Bucure%C8%99ti",
"rou/Oltenia_Craiova",
"isl/Knattspyrnuf%C3%A9lagi%C3%B0_Fram",
"lux/US_Hollerich_Bonnevoie",
"lux/Sporting_Club_Luxembourg",
"isl/Knattspyrnuf%C3%A9lag_Reykjav%C3%ADkur",
"lux/Racing_Club_Luxembourg",
"lux/CS_Fola_Esch",
"swe/GAIS",
"lux/Jeunesse_Esch",
"lux/Stade_Dudelange",
"isl/Valur_men%27s_football",
"swe/Helsingborgs_IF",
"lux/FCM_Young_Boys_Diekirch",
"mlt/Floriana_Liberty",
"sco/Clydebank_F.C._(1914)",
"mlt/Hibernians_F.C.",
"lux/CS_P%C3%A9tange",
"mlt/King%27s_Own_Malta_Regiment",
"isl/Knattspyrnuf%C3%A9lagi%C3%B0_V%C3%ADkingur",
"mlt/Army_Service_Corps",
"mlt/Cospicua_Rangers",
"rou/Venus_Bucure%C8%99ti",
"rou/Unirea_Tricolor_Bucure%C8%99ti",
"sco/Albion_Rovers_F.C.",
"mlt/Marsa_F.C.",
"mlt/Paola_United",
"lva/Kaiserwald",





"lva/YMCA",
"lux/Union_Luxembourg",
"swe/Hammarby_Fotboll",
"swe/IFK_Malm%C3%B6_Fotboll",
"lva/Union",
"lux/FA_Red_Boys_Differdange",
"mlt/Qormi_United",
"swe/IFK_Eskilstuna",
"mlt/Dockyard_Police",
"rou/Excelsior_Bucure%C8%99ti",
"rou/Educa%C8%9Bia_Fizic%C4%83_Bucure%C8%99ti",
"lux/US_Rumelange",
"lva/Karaskola",
"ltu/LFLS_Kaunas",
"irl/St._James%27s_Gate_F.C.",
"ltu/Aviacija_Kaunas",
"mlt/Malta_Police",
"ltu/Kovas_Kaunas",
"irl/Olympia_F.C._(Dublin)",
"ltu/LFLS_Kaunas_merge",
"irl/Jacobs_F.C.",
"ltu/Makabi_Kaunas",
"nir/Queens_Island_F.C.",
"irl/Dublin_United_F.C.",
"irl/Frankfort_F.C.",
"mlt/Sliema_Rangers",
"lux/Tricolore_Muhlenweg",
"lux/FC_Schifflange_95",
"irl/YMCA_F.C._(Dublin)",
"mlt/Old_Lions",
"ltu/BAB_(football_club)",
"irl/Shamrock_Rovers_F.C.",
"lva/JKS",
"irl/Shelbourne_United_F.C.",
"irl/Athlone_Town_A.F.C.",
"lva/LJS",
"lva/LSB",





"irl/Pioneers_F.C._(Dublin)",
"irl/Midland_Athletic_F.C.",
"sco/Alloa_Athletic_F.C.",
"irl/Rathmines_Athletic_F.C.",
"lva/Maccabi",
"lux/Union_05_Kayl-T%C3%A9tange",
"lva/RFK",
"lux/CA_Spora_Luxembourg",
"ltu/KSK_Kaunas",
"nir/Larne_F.C.",
"nir/Barn_F.C.",
"lva/Amatieris",
"nir/Ards_F.C.",
"lux/FC_Red_Black_Pfaffenthal",
"irl/Brooklyn_F.C._(Dublin)",
"nir/Newry_City_F.C.",
"lux/Eclair_Bettembourg",
"lva/ASK",
"irl/Cork_F.C.",
"nir/Portadown_F.C.",
"sco/Cowdenbeath_F.C.",
"sco/St_Johnstone_F.C.",
"swe/Landskrona_BoIS",
"swe/IK_Sleipner",
"mlt/Valletta_Rovers",
"lux/Progres_Grund",
"irl/Bray_Unknowns_F.C.",
"swe/V%C3%A4ster%C3%A5s_IK_Fotboll",
"lux/F91_Dudelange",
"irl/Brideville_F.C.",
"sco/Dundee_United_F.C.",
"swe/IFK_Uddevalla",
"lux/US_Esch",
"swe/IK_City",
"swe/IF_Elfsborg",





"sco/Dunfermline_Athletic_F.C.",
"swe/Westermalms_IF",
"irl/Dundalk_F.C.",
"lux/FC_Aris_Bonnevoie",
"lux/FC_Progr%C3%A8s_Niedercorn",
"isl/%C3%8D%C3%BEr%C3%B3ttabandalag_Vestmannaeyja",
"lva/Olimpija_Liep%C4%81ja",
"yug/HNK_Hajduk_Split",
"pol/Wis%C5%82a_Krak%C3%B3w",
"pol/1._FC_Kattowitz",
"pol/Warta_Pozna%C5%84",
"yug/OFK_Beograd",
"pol/Pogo%C5%84_Lw%C3%B3w_(1904)",
"pol/Legia_Warsaw",
"nir/Coleraine_F.C.",
"pol/Union_Touring_%C5%81%C3%B3d%C5%BA",
"yug/HA%C5%A0K",
"pol/%C5%81KS_%C5%81%C3%B3d%C5%BA",
"pol/Polonia_Warsaw",
"pol/TKS_Toru%C5%84",
"pol/Czarni_Lw%C3%B3w",
"nir/Bangor_F.C.",
"pol/Ruch_Chorz%C3%B3w",
"yug/NK_SA%C5%A0K_Napredak",
"yug/SAND_Subotica",
"pol/Hasmonea_Lw%C3%B3w",
"pol/KS_Warszawianka",
"sco/Bo%27ness_F.C.",
"yug/ND_Ilirija_1911",
"swe/Stattena_IF",
"pol/Jutrzenka_Krak%C3%B3w",
"yug/Gra%C4%91anski_Zagreb",
"pol/Cracovia_(football_club)",
"nir/Ballymena_F.C.",
"irl/Drumcondra_F.C.",
"lux/FC_Differdange_03",
"lva/LNJS",





"pol/%C5%9Al%C4%85sk_%C5%9Awi%C4%99toch%C5%82owice",
"yug/SK_Jugoslavija",
"esp/Athletic_Bilbao",
"ita/Inter_Milan",
"ita/Genoa_C.F.C.",
"esp/FC_Barcelona",
"pol/Garbarnia_Krak%C3%B3w",
"ita/Juventus_F.C.",
"ita/Torino_F.C.",
"esp/Arenas_Club_de_Getxo",
"esp/RCD_Espanyol",
"nir/Derry_City_F.C.",
"ita/A.S._Roma",
"ita/S.S.C._Napoli",
"ita/Bologna_F.C._1909",
"ita/U.S._Alessandria_Calcio_1912",
"ita/Brescia_Calcio",
"esp/Real_Madrid_C.F.",
"ita/F.C._Pro_Vercelli_1892",
"esp/Real_Uni%C3%B3n",
"ita/A.C._Milan",
"ita/Aurora_Pro_Patria_1919",
"ita/A.S._Livorno_Calcio",
"ita/Modena_F.C.",
"esp/Racing_de_Santander",
"ita/U.S._Triestina_Calcio_1918",
"swe/Sandvikens_IF",
"ita/S.S._Lazio",
"ita/Calcio_Padova",
"esp/Real_Sociedad",
"esp/CE_Europa",
"esp/Atl%C3%A9tico_de_Madrid",
"ita/U.S._Cremonese",
"irl/Dolphin_F.C._(Dublin)",
"lva/Riga_Wanderer",
"yug/H%C5%A0K_Concordia",
"irl/Waterford_United_F.C.",
"esp/Deportivo_Alav%C3%A9s",
"swe/Redbergslids_IK_Fotboll",





"ita/A.S._Casale_Calcio",
"sco/East_Fife_F.C.",
"ita/A.C._Legnano",
"pol/%C5%81TSG_%C5%81%C3%B3d%C5%BA",
"yug/Ma%C4%8Dva_%C5%A0abac",
"ltu/KSS_Klaip%C4%97da",
"ltu/Freya_Klaip%C4%97da",
"ita/ACF_Fiorentina",
"ltu/LGSF_Kaunas",
"ltu/Sveikata_Kybartai",
"esp/Valencia_CF",
"swe/Malm%C3%B6_FF",
"mlt/Sliema_Hotspurs",
"ita/A.S._Bari",
"pol/Lechia_Lw%C3%B3w",
"swe/Hallstahammars_SK",
"lva/C%C4%93su_Sporta_biedr%C4%ABba",
"ltu/Tauras_Kaunas",
"cze/SK_Slavia_Prague",
"cze/AC_Sparta_Prague",
"cze/FK_Viktoria_%C5%BDi%C5%BEkov",
"cze/DFC_Prag",
"cze/%C4%8CAFC_Prague",
"cze/SK_Libe%C5%88",
"cze/%C4%8Cechie_Karl%C3%ADn",
"cze/Bohemians_1905",
"cze/Nuselsk%C3%BD_SK",
"cze/FK_Meteor_Prague_VIII",
"cze/SK_Kladno",
"cze/SK_Slavoj_%C5%BDi%C5%BEkov",
"cze/SK_%C4%8Cechie_VIII",
"cze/Teplitzer_FK",
"cze/SK_N%C3%A1chod",
"cze/FC_Viktoria_Plze%C5%88",
"cze/SK_Plze%C5%88",
"cze/FC_Zbrojovka_Brno",
"cze/SK_Prost%C4%9Bjov",
"cze/AFK_Kol%C3%ADn",
"cze/%C5%A0K_Slovan_Bratislava",
"cze/SK_Moravsk%C3%A1_Slavia_Brno",





"cze/DSV_Saaz",
"cze/SC_Rusj_Uzhorod",
"cze/SK_Pardubice",
"cze/FC_Ban%C3%ADk_Ostrava",
"cze/M%C5%A0K_%C5%BDilina",
"cze/FC_Lokomot%C3%ADva_Ko%C5%A1ice",
"cze/FC_Fastav_Zl%C3%ADn",
"cze/SK_Olomouc_ASO",
"cze/FC_Spartak_Trnava",
"cze/SK_%C4%8Cesk%C3%A9_Bud%C4%9Bjovice",
"cze/Dukla_Prague",
"cze/FK_Teplice",
"cze/M%C5%A0K_Pova%C5%BEsk%C3%A1_Bystrica_(football)",
"cze/MFK_V%C3%ADtkovice",
"cze/1._FC_Tatran_Pre%C5%A1ov",
"cze/FK_%C3%9Ast%C3%AD_nad_Labem",
"cze/%C4%8CAFC_%C5%BDidenice",
"cze/FK_Inter_Bratislava",
"cze/K%C5%99%C3%ADdla_vlasti_Olomouc",
"cze/Tankista_Prague",
"cze/Slavoj_Liberec",
"cze/Slavia_Bratislava_VS",
"cze/Jiskra_Liberec",
"cze/FC_Hradec_Kr%C3%A1lov%C3%A9",
"cze/FC_VSS_Ko%C5%A1ice",
"cze/Rud%C3%A1_Hv%C4%9Bzda_Brno",
"cze/Dukla_Pardubice",
"cze/Slovan_Nitra",
"cze/TTS_Tren%C4%8D%C3%ADn",
"cze/FC_LeRK_Brno",
"cze/FK_Fotbal_T%C5%99inec",
"cze/FK_Motorlet_Prague",
"cze/SK_Ba%C5%A5ov_1930",
"cze/FK_Dukla_Bansk%C3%A1_Bystrica",
"cze/FK_Pardubice_1899",
"cze/FK_Jablonec",
"cze/MFK_Fr%C3%BDdek-M%C3%ADstek",
"cze/FK_Hv%C4%9Bzda_Cheb",
"cze/FC_Petr%C5%BEalka",
"cze/SK_Sigma_Olomouc",





"cze/FC_DAC_1904_Dunajsk%C3%A1_Streda",
"dnk/%C3%98sterbro_Boldklub_(1887-1893)",
"dnk/Akademisk_Boldklub",
"dnk/Boldklubben_Arrow",
"dnk/Boldklubben_Frem",
"dnk/Boldklubben_Fri",
"dnk/Boldklubben_Haabet",
"dnk/Christianshavn_Boldklub",
"dnk/Kj%C3%B8benhavns_Boldklub",
"dnk/Melchioraner_Boldklubben",
"dnk/Olympia_(Denmark_football_club)",
"dnk/Boldklubben_af_1893",
"dnk/%C3%98sterbros_Boldklub",
"dnk/Boldklubben_Dana",
"dnk/Boldklubben_1903",
"dnk/Horsens_fS",
"dnk/B_1901",
"dnk/AaB_Fodbold",
"dnk/Odense_Boldklub",
"dnk/Kors%C3%B8r_Boldklub",
"dnk/Aarhus_Gymnastikforening",
"dnk/Fremad_Amager",
"dnk/Esbjerg_fB",
"dnk/Skovshoved_IF",
"dnk/Helsing%C3%B8r_IF",
"dnk/Hellerup_IK",
"dnk/Vejen_SF",
"dnk/K%C3%B8ge_BK",
"dnk/Boldklubben_1909",
"dnk/Arbejdernes_Idr%C3%A6tsklub_Aarhus",
"dnk/Vejle_Boldklub",
"dnk/KFUM%27s_Boldklub_(Copenhagen)",
"dnk/Frederikshavn_fI",
"dnk/Boldklubben_1913",
"dnk/Br%C3%B8nsh%C3%B8j_BK",
"dnk/Hvidovre_IF",
"dnk/Randers_Sportsklub_Freja",
"dnk/N%C3%A6stved_BK",
"dnk/Holb%C3%A6k_B%26I",
"dnk/Slagelse_B%26I",





"dnk/Vanl%C3%B8se_IF",
"dnk/Kastrup_Boldklub",
"dnk/IK_Skovbakken",
"dnk/Ikast_FS",
"dnk/Lyngby_BK",
"dnk/Herf%C3%B8lge_BK",
"dnk/Viborg_FF",
"dnk/Br%C3%B8ndby_IF",
"dnk/Kolding_IF",
"dnk/Herning_Fremad",
"dnk/Silkeborg_IF",
"dnk/FC_K%C3%B8benhavn",
"dnk/Aarhus_Fremad",
"dnk/FC_Midtjylland",
"dnk/Sønderjyske_Fodbold",
"dnk/Farum_BK",
"dnk/Randers_FC",
"dnk/HB_K%C3%B8ge",
"dnk/FC_Vestsj%C3%A6lland",
"dnk/Hobro_IK",
"dnk/Vendsyssel_FF",
"est/VS_Sport_Tallinn",
"est/Tallinna_Jalgpalliklubi",
"est/ESS_Kalev_Tallinn",
"est/VK_Merkur_Tallinn",
"est/SK_Estika_Tallinn",
"est/Tartu_Jalgpalliklubi",
"est/KS_V%C3%B5itleja_Narva",
"est/VVS_Puhkekodu_Tallinn",
"est/Narva_THK",
"est/JS_Estonia_Tallinn",
"est/PK_Ol%C3%BCmpia_Tartu",
"est/JK_Tervis_P%C3%A4rnu",
"est/S%C3%9C_Esta_Tallinn",
"est/%C3%9Cle_Eestilise_Noorte_%C3%9Chenduse_Tallinna_Osakond",
"est/Tartu_Prefektuuri_Spordiring",
"est/Narva_Spordiklubi",
"est/Tallinna_Spordiklubi",
"est/Tartu_Politsei_Spordiring",
"est/Tallinna_JK_D%C3%BCnamo",





"est/Baltic_Fleet",
"est/Rifle_corps_(Soviet)_2",
"est/Rifle_corps_(Soviet)_1",
"est/Tallinna_Spartak",
"est/Rakvere_D%C3%BCnamo",
"est/P%C3%A4rnu_Kalev",
"est/Officers%27_Club_of_Tallinn",
"est/Tallinna_Esto",
"est/Tartu_Kalev_(football_club)",
"est/Viljandi_D%C3%BCnamo",
"est/Narva_D%C3%BCnamo",
"est/Soviet_Air_Forces_Club_Sokol",
"est/Narva_Kalev",
"est/Kohtla-J%C3%A4rve_Kalev",
"est/Tartu_%C3%9CSK",
"est/J%C3%A4rvakandi_Kalev",
"est/Viljandi_Spartak",
"est/Kivi%C3%B5li_Kalev",
"est/Tartu_D%C3%BCnamo",,
"est/Rakvere_Kalev",
"est/%C3%9Clemiste_Kalev",
"est/Tallinna_Punane_Koit",
"est/JK_Sillam%C3%A4e_Kalev",
"est/FC_Norma_Tallinn",
"est/Kohtla-J%C3%A4rve_PK",
"est/Viljandi_Kalev",
"est/Narva_Kreenholm",
"est/T%C3%BCri_J%C3%B5ud",
"est/Viljandi_J%C3%B5ud",
"est/Tallinna_JK_Tempo",
"est/Aseri_Kalev",
"est/EAT_Tallinn",
"est/Kivi%C3%B5li_Kombinaat",
"est/Kopli_D%C3%BCnamo",
"est/Valga_Kalev",
"est/Aseri_Keraamikatehas",
"est/Tartu_Remonditehas",
"est/Tallinna_Tekstiil",
"est/Narva_Energeetik",
"est/Tallinna_Start",





"est/J%C3%B5hvi_Kaevur",
"est/Tallinna_SK_Dvigatel",
"est/JHK_Kohtla-J%C3%A4rve_Keemik",
"est/Valga_Lokomotiv",
"est/Narva_Baltika",
"est/Narva_Energoremont",
"est/Kohtla-J%C3%A4rve_EPT",
"est/Aseri_SK",
"est/Kohtla-J%C3%A4rve_Raudbetoonitehas",
"est/P%C3%A4rnu_Kalakombinaat",
"est/J%C3%B5hvi_Estonia_Kaevandus",
"est/Tartu_Kontrollaparaaditehas",
"est/Tallinna_Autobussipark",
"est/Tartu_Katseremonditehas",
"est/TPI_Tallinn",
"est/Narva_Energia",
"est/Kohtla-J%C3%A4rve_Betoonitehas",
"est/FK_Viljandi",
"est/Kohtla-J%C3%A4rve_Ehitaja",
"est/Tallinna_Elektrotehnika",
"est/P%C3%A4rnu_KEK",
"est/JK_Narva_Trans",
"est/Kivi%C3%B5li_Autoveod",
"est/P%C3%A4rnu_Kalakombinaat/MEK",
"est/Tallinna_FC_Zvezda",
"est/Tallinna_KK_Majak",
"est/Tallinna_Elektrotehnik",
"est/Kohtla-J%C3%A4rve_RMT",
"est/J%C3%B5hvi_Estonia_Kaevandus/RMT",
"est/JK_Eesti_P%C3%B5levkivi_J%C3%B5hvi",
"est/FC_TVMK",
"est/FC_Flora_Tallinn",
"est/Narva_JK_Trans",
"est/Estonia_J%C3%B5hvi",
"est/P%C3%A4rnu_Linnameeskond",
"est/Viljandi_JK_Tulevik",
"est/Baltika_Narva",
"est/Tartu_JK_Merkuur",
"est/FC_Nikol_Tallinn",
"est/KSK_Vigri_Tallinn",





"est/Spordiselts_EsDAG",
"est/FC_D%C3%BCnamo_Tallinn",
"est/JK_Viljandi_Tulevik",
"est/JK_Tallinna_Sadam",
"est/FC_Tevalte_Tallinn",
"est/FC_Lantana_Tallinn",
"est/P%C3%A4rnu_JK",
"est/FC_DAG",
"est/Lelle_SK",
"est/JK_Vall_Tallinn",
"est/FC_Levadia_Maardu",
"est/FC_Lootus_Kohtla-J%C3%A4rve",
"est/FC_Kuressaare",
"est/FC_Valga",
"est/FC_Levadia_II_Tallinn",
"est/FC_Levadia_P%C3%A4rnu",
"est/Tartu_FC_Merkuur",
"est/Alutaguse_Lootus",
"est/Tartu_JK_Tammeka",
"est/P%C3%A4rnu_JK_Vaprus",
"est/FC_Ajax_Lasnam%C3%A4e",
"est/FC_Valga_Warrior",
"est/N%C3%B5mme_Kalju_FC",
"est/Paide_Linnameeskond",
"est/FC_Viljandi_(2011)",
"est/FC_Infonet",
"est/J%C3%B5hvi_FC_Lokomotiv",
"est/Rakvere_JK_Tarvas",
"est/FCI_Levadia_Tallinn",
"est/Maardu_Linnameeskond",
"est/Tallinna_JK_Legion",
"est/Harju_JK_Laagri",


/************************************************************ FINLAND */
/*Åbo_IFK*/"fin/%C3%85IFK_Turku",
/*AC_Allianssi*/"fin/AC_Allianssi",
/*AC_Oulu*/"fin/AC_Oulu",
/*Atlantis_FC*/"fin/Atlantis_FC",
/*Ekenäs_IF*/"fin/EIF_Tammisaari",
/*Elo_Kuopio*/"fin/Elo_Kuopio",
/*FC_Haka*/"fin/FC_Haka",
/*FC_Hämeenlinna*/"fin/FC_H%C3%A4meenlinna",
/*FC_Honka*/"fin/FC_Honka",
/*FC_Inter_Turku*/"fin/FC_Inter_Turku",
/*FF_Jaro*/"fin/Jaro_Pietarsaari",
/*FC_Jazz*/"fin/PPT_Pori",
/*FC_Jokerit*/"fin/FC_Jokerit",
/*FC_Kiffen_08*/"fin/KIF_Helsinki",
/*FC_KooTeePee*/"fin/FC_KooTeePee",
/*FC_Kuusysi*/"fin/FC_Kuusysi",
/*FC_Lahti*/"fin/FC_Lahti",
/*FC_Oulu*/"fin/FC_Oulu",
/*FC_Viikingit*/"fin/FC_Viikingit",
/*FinnPa*/"fin/FinnPa_Helsinki",
/*GBK_Kokkola*/"fin/GBK_Kokkola",
/*Hangö_IK*/"fin/HIK_Hanko",
/*Helsingin_Jalkapalloklubi*/"fin/HJK_Helsinki",
/*Helsingin_Palloseura*/"fin/HPS_Helsinki",
/*Helsingin_Ponnistus*/"fin/Ponnistus_Helsinki",
/*HIFK*/"fin/HIFK",
/*HIFK_Fotboll*/"fin/HIFK_Fotboll",
/*IF_Drott*/"fin/IF_Drott",
/*IFK_Mariehamn*/"fin/IFK_Mariehamn",
/*Into_Kemi*/"fin/Into_Kemi",
/*Ilves_(football)*/"fin/IKissat_Tampere",
/*Jäntevä_Kotka*/"fin/J%C3%A4ntev%C3%A4_Kotka",
/*JJK_Jyväskylä*/"fin/Jyv%C3%A4skyl%C3%A4n_Jalkapalloklubi",
/*Kajaanin_Palloilijat*/"fin/KaPa_Kajaani",
/*Kemi_City_F.C.*/"fin/KePS_Kemi",
/*Kokkolan_Palloveikot*/"fin/Kokkolan_Palloveikot",
/*Koparit*/"fin/KPT_Kuopio",
/*Kotkan_Reipas*/"fin/KoRe_Kotka",
/*Kotkan_Työväen_Palloilijat*/"fin/KTP_Kotka",
/*Kullervo_Helsinki*/"fin/Kullervo_Helsinki",
/*Kuopion_Palloseura*/"fin/KuPS",
/*Kuusankosken_Kumu*/"fin/Kumu_Kuusankoski",
/*Makkabi_Helsinki*/"fin/Makkabi_Helsinki",
/*Mikkelin_Pallo-Kissat*/"fin/Mikkelin_Pallo-Kissat",
/*Mikkelin_Palloilijat*/"fin/MP_Mikkeli",
/*Myllykosken_Pallo_−47*/"fin/MyPa",
/*Oulun_Palloseura*/"fin/Oulun_Palloseura",
/*Oulun_Työväen_Palloilijat*/"fin/OTP_Oulu",
/*Pallo-Pojat_Juniorit*/"fin/PPojat_Helsinki",
/*PK-35_Vantaa_(men)*/"fin/PK-35_Vantaa_(men)",
/*Porin_Ässät_(men%27s_football)*/"fin/%C3%84ss%C3%A4t_(football)",
/*Pyrkivä_Turku*/"fin/Pyrkiv%C3%A4_Turku",
/*Reipas_Lahti*/"fin/Reipas_Lahti",
/*Rosenlewin_Urheilijat-38*/"fin/RU-38_(sports_club)",
/*Rovaniemen_Palloseura*/"fin/RoPS_Rovaniemi",
/*Seinäjoen_Jalkapallokerho*/"fin/Sein%C3%A4joen_Jalkapallokerho",
/*Sepsi-78*/"fin/Sepsi-78",
/*Sudet*/"fin/Sudet_Viipuri",
/*Tampere_United*/"fin/Tampere_United",
/*Tampereen_Pallo-Veikot*/"fin/Tampereen_Pallo-Veikot",
/*Tampereen-Viipurin_Ilves-Kissat*/"fin/Ilves-Kissat",
/*TaPa*/"fin/TaPa",
/*TKT_Tampere*/"fin/TKT_Tampere",
/*Toverit_Helsinki*/"fin/Toverit_Helsinki",
/*TP-47*/"fin/TP-47",
/*TP-Seinäjoki*/"fin/TP-Sein%C3%A4joki",
/*Turun_Pallokerho*/"fin/TPK_Turku",
/*Turun_Palloseura*/"fin/Turun_Palloseura",
/*Turun_Urheiluliitto*/"fin/UL_Turku",
/*Turun_Toverit*/"fin/TuTo_Turku",
/*Turun_Weikot*/"fin/TuWe_Turku",
/*Vaasan_Palloseura*/"fin/Vaasan_Palloseura",
/*ViPS_Viipuri*/"fin/ViPS_Viipuri",
/*Vasa_IFK*/"fin/VIFK_Vaasa",
/*Viipurin_Reipas*/"fin/Viipurin_Reipas",

/************************************************************ HUNGARY */
/*33_FC*/"hun/33_*/FC",
/*Bocskai_FC*/"hun/Bocskai_FC",
/*Budapest_Honvéd_FC*/"hun/Budapest_Honv%C3%A9d_FC",
/*Budapesti_AK*/"hun/Budapesti_AK",
/*Budapesti_EAC*/"hun/Budapesti_EAC",
/*Budapesti_MÁVAG_SK*/"hun/Budapesti_M%C3%81VAG_SK",
/*Budapesti_Postás_SE*/"hun/Budapesti_Post%C3%A1s_SE",
/*Budapesti_SC*/"hun/Budapesti_SC",
/*Budapesti_TC*/"hun/Budapesti_TC",
/*Erzsébeti_TC*/"hun/Erzs%C3%A9beti_TC",
/*Ferencvárosi_TC*/"hun/Ferencv%C3%A1rosi_TC",
/*Fővárosi_TK*/"hun/F%C5%91v%C3%A1rosi_TK",
/*III._Kerületi_TVE*/"hun/III._Ker%C3%BCleti_TUE",
/*Magyar_AC*/"hun/Magyar_AC",
/*Magyar_Úszó_Egylet*/"hun/Magyar_%C3%9Asz%C3%B3_Egylet",
/*Miskolci_AK*/"hun/Miskolci_AK",
/*MTK_Budapest_FC*/"hun/MTK_Budapest_FC",
/*Műegyetemi_AFC*/"hun/M%C5%B1egyetemi_AFC",
/*Nemzeti_SC*/"hun/Nemzeti_SC",
/*Pécs-Baranya_FC*/"hun/P%C3%A9cs-Baranya_FC",
/*Sabaria_FC*/"hun/Sabaria_FC",
/*Somogy_FC*/"hun/Somogy_FC",
/*Szegedi_AK*/"hun/Szegedi_AK",
/*Terézvárosi_TC*/"hun/Ter%C3%A9zv%C3%A1rosi_TC",
/*Törekvés_SE*/"hun/T%C3%B6rekv%C3%A9s_SE",
/*Typographia_SC*/"hun/Typographia_SC",
/*Újpest_FC*/"hun/%C3%9Ajpest_FC",
/*Újpesti_Törekvés_SE*/"hun/%C3%9Ajpesti_T%C3%B6rekv%C3%A9s_SE",
/*Vasas_SC*/"hun/Vasas_SC",
/*VII._Kerületi_SC*/"hun/VII._Ker%C3%BCleti_SC",
/*Vívó_és_Atlétikai_Club*/"hun/V%C3%ADv%C3%B3_%C3%A9s_Atl%C3%A9tikai_Club",
/*Zuglói_AC*/"hun/Turul_FC",





];

redirects = [

["hun/MTK_Budapest_FC","hun/MTK_Hung%C3%A1ria_FC"],
["hun/Turul_FC","hun/Zugl%C3%B3i_AC"],



["fin/Sudet_Viipuri","fin/Sudet_Helsinki"],
["fin/KuPS","fin/Kuopion_Palloseura"],
["fin/KTP_Kotka","fin/Kotkan_Ty%C3%B6v%C3%A4en_Palloilijat"],
["fin/Reipas_Lahti","fin/Reipas_Lahti#Football"],
["fin/IKissat_Tampere","fin/FC_Ilves"],
["fin/%C3%85IFK_Turku","fin/%C3%85bo_IFK"],
["fin/HPS_Helsinki","fin/Helsingin_Palloseura#Football"],
["fin/KIF_Helsinki","fin/FC_Kiffen_08#Football"],
["fin/KIF_Helsinki","fin/Kiffen"],
["fin/IKissat_Tampere","fin/Ilves"],
["fin/KPT_Kuopio","fin/Koparit_Kuopio"],
["fin/RoPS_Rovaniemi","fin/RoPS"],
["fin/Jaro_Pietarsaari","fin/Jaro_Jakobstad"],
["fin/PPT_Pori","fin/FC_Jazz_Pori"],
["fin/Ponnistus_Helsinki","fin/Ponnistus"],
["fin/PPT_Pori","fin/FC_Jazz"],
["fin/MyPa","fin/Myllykosken_Pallo_%E2%88%9247"],
["fin/FinnPa_Helsinki","fin/FinnPa"],
["fin/Jaro_Pietarsaari","fin/FF_Jaro"],
["fin/RoPS_Rovaniemi","fin/Rovaniemen_Palloseura"],
["fin/HJK_Helsinki","fin/Helsingin_Jalkapalloklubi"],
["fin/IKissat_Tampere","fin/Ilves_(football)"],
["fin/MP_Mikkeli","fin/Mikkelin_Palloilijat"],
["fin/MyPa","fin/MYPA"],
["fin/KePS_Kemi","fin/Palloseura_Kemi_Kings"],
["fin/Jyv%C3%A4skyl%C3%A4n_Jalkapalloklubi","fin/JJK_Jyv%C3%A4skyl%C3%A4"],
["est/JK_Tervis_P%C3%A4rnu","est/P%C3%A4rnu_Tervis"],
["est/ESS_Kalev_Tallinn","est/JK_Tallinna_Kalev"],
["est/Tallinna_JK_D%C3%BCnamo","est/JK_D%C3%BCnamo_Tallinn"],
["est/Kohtla-J%C3%A4rve_PK","est/Kohtla-J%C3%A4rve_P%C3%B5levkivikombinaat"],
["est/JHK_Kohtla-J%C3%A4rve_Keemik","est/Kohtla-J%C3%A4rve_JK_Keemik"],
["est/FK_Viljandi","est/Viljandi_FK"],
["est/FC_TVMK","est/FC_TVMK_Tallinn"],
["est/FC_Flora_Tallinn","est/FC_Flora"],
["est/FC_Levadia_Maardu","est/FC_Levadia_Tallinn"],
["est/Tartu_JK_Merkuur","est/JK_Maag_Tartu"],
["est/Tartu_JK_Merkuur","est/JK_Maag_Tammeka_Tartu"],
["est/FC_Infonet","est/FCI_Tallinn"],
["dnk/%C3%98sterbros_Boldklub","dnk/%C3%98sterbros_BK"],
["dnk/B_1901","dnk/Boldklubben_1901"],
["dnk/Br%C3%B8nsh%C3%B8j_BK","dnk/Br%C3%B8nsh%C3%B8j_Boldklub"],
["dnk/N%C3%A6stved_BK","dnk/N%C3%A6stved_IF"],
["dnk/B_1901","dnk/Nyk%C3%B8bing_Falster_Boldklub_af_1901"],
["dnk/Boldklubben_1903","dnk/B_1903"],
["dnk/Kastrup_Boldklub","dnk/Kastrup_BK"],
["dnk/Odense_Boldklub","dnk/Odense_BK"],
["dnk/Boldklubben_Frem","dnk/BK_Frem"],
["dnk/Vejle_Boldklub","dnk/Vejle_BK"],
["dnk/Aarhus_Gymnastikforening","dnk/Aarhus_GF"],
["dnk/Boldklubben_1909","dnk/B_1909"],
["dnk/Lyngby_BK","dnk/Lyngby_Boldklub"],
["dnk/Boldklubben_af_1893","dnk/Boldklubben_1893"],
["dnk/Randers_Sportsklub_Freja","dnk/Randers_Freja"],
["dnk/Aarhus_Gymnastikforening","dnk/Aarhus_Gymnastik_Forening"],
["dnk/Lyngby_BK","dnk/Lyngby_FC"],
["dnk/Fremad_Amager","dnk/BK_Fremad_Amager"],
["dnk/Farum_BK","dnk/FC_Nordsj%C3%A6lland"],
["dnk/Herf%C3%B8lge_BK","dnk/Herf%C3%B8lge_Boldklub"],
["dnk/FC_K%C3%B8benhavn","dnk/F.C._Copenhagen"],
["dnk/Horsens_fS","dnk/AC_Horsens"],
["dnk/Sønderjyske_Fodbold","dnk/S%C3%B8nderjyskE_Fodbold"],
["dnk/Helsing%C3%B8r_IF","dnk/FC_Helsing%C3%B8r"],
["cze/SK_N%C3%A1chod","cze/FK_N%C3%A1chod"],
["cze/AC_Sparta_Prague","cze/Sparta_Prague"],
["cze/Slovan_Nitra","cze/FC_Nitra"],
["cze/FC_VSS_Ko%C5%A1ice","cze/MFK_Ko%C5%A1ice"],
["cze/SK_%C4%8Cesk%C3%A9_Bud%C4%9Bjovice","cze/SK_Dynamo_%C4%8Cesk%C3%A9_Bud%C4%9Bjovice"],
["cze/MFK_V%C3%ADtkovice","cze/TJ_V%C3%ADtkovice"],
["cze/FC_Zbrojovka_Brno","cze/FC_Boby_Brno"],
["alb/Luft%C3%ABtari_Gjirokast%C3%ABr","alb/KF_Luft%C3%ABtari_Gjirokast%C3%ABr"],
["alb/KF_Pogradeci","alb/KS_Pogradeci"],
["alb/KF_Tekstilisti_Stalin","alb/KS_Tekstilisti_Stalin_Yzberisht"],
["alb/KF_Naft%C3%ABtari","alb/Naft%C3%ABtari_Ku%C3%A7ov%C3%AB"],
["alb/Shkendija_Tirane","alb/Shk%C3%ABndija_Tiran%C3%AB"],
["alb/KS_Lushnja","alb/KF_Lushnja"],
["alb/KF_Elbasani","alb/KS_Elbasani"],
["alb/Shkumbini_Peqin","alb/KF_Shkumbini"],
["alb/FK_Tomori_Berat","alb/KF_Tomori"],
["alb/KF_Apolonia_Fier","alb/FK_Apolonia_Fier"],
["alb/Luft%C3%ABtari_Gjirokast%C3%ABr","alb/Luft%C3%ABtari_Gjirokast%C3%ABr_FC"],
["alb/Luft%C3%ABtari_Gjirokast%C3%ABr","alb/KF_Luft%C3%ABtari"],
["alb/KF_Bylis_Ballsh","alb/KF_Bylis"],
["alb/Flamurtari_Vlor%C3%AB","alb/Flamurtari_FC"],
["alb/FK_Egnatia","alb/KF_Egnatia"],
["alb/FK_Dinamo_Tirana","alb/FC_Dinamo_City"],
["aut/SV_Amateure","aut/FK_Austria_Wien"],
["aut/SC_Rudolfsh%C3%BCgel","aut/https://de.wikipedia.orgSpC_Rudolfsh%C3%BCgel"],
["aut/SC_Wacker","aut/FC_Admira_Wacker_M%C3%B6dling"],
["aut/Post_SV","aut/Post_SV_Wien"],
["aut/Salzburger_AK_1914","aut/Salzburger_AK"],
["aut/Wiener_Sportclub","aut/Wiener_Sport-Club"],
["aut/VfB_Admira_Wacker_M%C3%B6dling","aut/FC_Admira_Wacker_M%C3%B6dling#SK_Admira_Vienna"],
["aut/Wiener_AC","aut/Wiener_AC#Football"],
["aut/FC_Dornbirn","aut/FC_Dornbirn_1913"],
["aut/SV_Austria_Salzburg","aut/FC_Red_Bull_Salzburg"],
["aut/Schwarz-Wei%C3%9F_Bregenz","aut/FC_Vorarlberg"],
["aut/V%C3%96EST_Linz","aut/FC_Linz"],
["aut/Schwarz-Wei%C3%9F_Bregenz","aut/SC_Bregenz"],
["aut/LASK_Linz","aut/LASK"],
["aut/WSG_Swarovski_Tirol","aut/WSG_Tirol"],
["bel/R._L%C3%A9opold_Uccle_Forestoise","bel/L%C3%A9opold_FC"],
["bel/R.E._Sport%27s_Club","bel/Royal_Excelsior_Sports_Club"],
["bel/Daring_Club_de_Bruxelles","bel/R._Daring_Club_Molenbeek"],
["bel/Club_Brugge","bel/Club_Brugge_K.V."],
["bel/R._Antwerp_F.C.","bel/Royal_Antwerp_FC"],
["bel/R.F.C._Tilleur","bel/Tilleur_FC"],
["bel/R._Union_Saint-Gilloise","bel/Royale_Union_Saint-Gilloise"],
["bel/R._Antwerp_F.C.","bel/Royal_Antwerp_F.C."],
["bel/K._Sint-Truidense_V.V.","bel/Sint-Truidense_V.V."],
["bel/Club_Brugge","bel/Club_Brugge_KV"],
["bel/K_Berchem_Sport","bel/K._Berchem_Sport"],
["bel/Beringen_FC","bel/K._Beringen_F.C."],
["bel/R.F.C._de_Li%C3%A8ge","bel/RFC_Li%C3%A8ge"],
["bel/K.F.C._Germinal_Beerschot","bel/Beerschot_AC"],
["bel/R.F.C._Tilleur","bel/R.F.C._Tilleur-Saint-Nicolas"],
["bel/R.W.D._Molenbeek","bel/R._White_Daring_Molenbeek"],
["bel/K.F.C._Germinal_Beerschot","bel/Germinal_Ekeren"],
["bel/R.S.C._Anderlecht","bel/RSC_Anderlecht"],
["bel/R._Antwerp_F.C.","bel/Antwerp_FC"],
["bel/K.A.A._Gent","bel/AA_Gent"],
["bel/Lierse_S.K.","bel/Lierse_SK"],
["bel/Cercle_Brugge_K.S.V.","bel/Cercle_Brugge"],
["bel/K.S.V._Waregem","bel/KSV_Waregem"],
["bel/K.S.K._Beveren","bel/KSK_Beveren"],
["bel/R._Charleroi_S.C.","bel/Sporting_Charleroi"],
["bel/K.S.C._Lokeren_Oost-Vlaanderen","bel/KSC_Lokeren"],
["bel/R.F.C._de_Li%C3%A8ge","bel/RFC_de_Li%C3%A8ge"],
["bel/K.R.C._Genk","bel/KRC_Genk"],
["bel/K.V._Kortrijk","bel/KV_Kortrijk"],
["bel/V.C._Eendracht_Aalst_2002","bel/Eendracht_Aalst"],
["bel/K_Boom_FC","bel/K._Boom_F.C."],
["bel/KV_Mechelen","bel/Y.R._K.V._Mechelen"],
["bel/V.C._Eendracht_Aalst_2002","bel/K.S.C._Eendracht_Aalst"],
["bel/V.C._Eendracht_Aalst_2002","bel/SC_Eendracht_Aalst"],
["bel/V.C._Eendracht_Aalst_2002","bel/S.C._Eendracht_Aalst"],
["bel/FC_Brussels","bel/F.C._Molenbeek_Brussels_Strombeek"],
["bel/S.V._Zulte-Waregem","bel/S.V._Zulte_Waregem"],
["bel/KV_Mechelen","bel/K.V._Mechelen"],
["bel/K.F.C._Germinal_Beerschot","bel/Beerschot_A.C."],
["bel/Royal_Mouscron-P%C3%A9ruwelz","bel/Royal_Excel_Mouscron"],
["eng/Wolverhampton_Wanderers_F.C.","eng/Wolverhampton_Wanderers"],
["eng/Aston_Villa_F.C.","eng/Aston_Villa"],
["eng/Leeds_United_F.C.","eng/Leeds_United_A.F.C."],
["eng/Tottenham_Hotspur_F.C.","eng/Tottenham_Hotspur_F.C"],
["eir/Bohemian_F.C.","eir/Bohemian_Dublin"],
["sco/Albion_Rovers_F.C.","sco/Albion_Rovers_F.C._(Scotland)"],
["mlt/%C4%A6amrun_Spartans_F.C.","mlt/Hamrun_Spartans_F.C."],
["irl/Cork_F.C.","irl/Fordsons_F.C."],
["irl/Brideville_F.C.","irl/Brideville_FC"],
["mlt/Cottonera_F.C.","mlt/Cottonera"],
["lva/RFK","lva/R%C4%ABgas_FK"],
["lva/LSB","lva/LSB_R%C4%ABga"],
["irl/St._James%27s_Gate_F.C.","irl/St_James%27s_Gate_F.C."],
["yug/HNK_Hajduk_Split","yug/Hajduk_Split"],
["yug/OFK_Beograd","yug/BSK_Beograd"],
["yug/NK_SA%C5%A0K_Napredak","yug/SA%C5%A0K"],
["pol/Pogo%C5%84_Lw%C3%B3w_(1904)","pol/Pogo%C5%84_Lw%C3%B3w"],
["pol/KS_Warszawianka","pol/Warszawianka_Warszawa"],
["lva/ASK","lva/FK_ASK"],
["lva/Union","lva/Union_Riga"],
["ita/F.C._Pro_Vercelli_1892","ita/U.S._Pro_Vercelli_Calcio"],
["ita/U.S._Triestina_Calcio_1918","ita/U.S._Triestina_Calcio"],
["irl/Waterford_United_F.C.","irl/Waterford_F.C."],
["lva/Amatieris","lva/Amatieris_R%C4%ABga"]

];